name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test-cl-quil:
    name: Test cl-quil
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          docker build -t rigetti/quilc:${GITHUB_SHA} .
          docker run --rm --entrypoint=make rigetti/quilc:${GITHUB_SHA} test-cl-quil
          docker rmi rigetti/quilc:${GITHUB_SHA}

  test-quilc:
    name: Test quilc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          sudo apt install sbcl
          make quicklisp
          sudo make install-test-deps
          make test-quilc

  test-quilt:
    name: Test quilt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          sudo apt install sbcl
          make quicklisp
          sudo make install-test-deps
          make test-quilt

